version: '2'
services:
  app:
    image: node:6
    volumes:
      - .:/app
    command: /app/wait-for-it/wait-for-it.sh mysql:3306 -- node /app/src/spider/index.js

  mysql:
    image: mysql
## if you want to persist your mysql databases, uncomment next lines
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spider

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql

