version: '2'
services:
  app:
    image: node:6
    ports:
      - "8091:3000"
    volumes:
      - .:/app
    command: node /app/src/server/index.js
    environment:
      - DATABASE_TYPE=mysql
      - MYSQL_PASSWORD=spider
      - MYSQL_USERNAME=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306

  mysql:
    image: mysql
## if you want to persist your mysql databases, uncomment next lines
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spider

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql

